### ISSUE TITLE
建议封一个Release的包，方便快速上手

### ISSUE THREAD

**Issue by langren1353** [mcg-helper/mcg-helper#31]
当有了快速上手的案例之后，才会有更多的小白用户介入，反推导致项目会有更多的用户量

**Comment by langren1353** [comment]
项目本身实际上是一个非常不错的项目

**Comment by mcg-helper** [comment]
欢迎您的来电！    您好，由于近期邮件数量较多，无法亲自回复你的邮件，请谅解！我们将会认真阅读您的信息后，尽快给您回复，感谢您的支持！

**Comment by mcg-helper** [comment]
很高兴收到你的反馈，早期是有Release包，双击即可运行，前几年闭源，后面没有在维护了&nbsp;


MCG
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 中午1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mcg-helper/mcg-helper] 建议封一个Release的包，方便快速上手 (Issue #31)





 
项目本身实际上是一个非常不错的项目

**Comment by mcg-helper** [comment]
欢迎您的来电！    您好，由于近期邮件数量较多，无法亲自回复你的邮件，请谅解！我们将会认真阅读您的信息后，尽快给您回复，感谢您的支持！
